music/urls.py
from django.urls import path
from . import views

app_name = 'music'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('album/create/', views.AlbumCreate.as_view(), name='album-create'),
    path('album/<int:pk>/update/', views.AlbumUpdate.as_view(), name='album-update'),
    path('album/<int:pk>/delete/', views.AlbumDelete.as_view(), name='album-delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=250)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def __str__(self):
        return self.album_title

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/forms.py
from django.forms import ModelForm, FileInput
from .models import Album


class CreateUpdateAlbumForm(ModelForm):
    class Meta:
        model = Album
        fields = '__all__'
        widgets = {
            'album_logo': FileInput(attrs={'class': 'btn blue-grey darken-4', }),
        }

music/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import Album
from .forms import CreateUpdateAlbumForm


class HomeView(generic.ListView):
    template_name = 'music/home.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(generic.CreateView):
    form_class = CreateUpdateAlbumForm
    template_name = 'music/album_form.html'

    def get_context_data(self, **kwargs):
        kwargs['naming'] = 'Create'
        context = super(AlbumCreate, self).get_context_data(**kwargs)
        return context


class AlbumUpdate(generic.UpdateView):
    model = Album
    form_class = CreateUpdateAlbumForm
    template_name = 'music/album_form.html'

    def get_context_data(self, **kwargs):
        kwargs['naming'] = 'Update'
        context = super(AlbumUpdate, self).get_context_data(**kwargs)
        return context


class AlbumDelete(generic.DeleteView):
    model = Album
    context_object_name = 'album'
    success_url = reverse_lazy('music:home')

music/templates/music/album_confirm_delete.html
{% extends 'music/base.html' %}

{% block title %} Delete Album {% endblock title%}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ album.artist }} - {{ album.album_title }}"?</p>
    <button class="btn orange darken-4" type="submit">Confirm</button>
    <a href="{% url 'music:home' %}" class="btn blue-grey darken-4">Cancel</a>
</form>
{% endblock content%}

music/templates/music/album_form.html
{% extends 'music/base.html' %}

{% block title %} {{ naming }} Album {% endblock title %}

{% block content %}
    <div class="row">
        <div class="input-field col s12 m6 offset-m3">
            <form action="" method="POST"enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn waves-effect waves-light blue-grey darken-4" type="submit">{{ naming }} Album</button>
            </form>
        </div>
    </div>
{% endblock content%}

music/templates/music/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Righteous&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'music/style.css' %}">
    <title>{% block title %} SyM - Share Your Music {% endblock title %}</title>
</head>
<body>

<nav>
    <div class="nav-wrapper blue-grey darken-4">
        <div class="container">
            <a href="{% url 'music:home' %}" class="brand-logo left title-font">SyM</a>
            <a href="#" data-target="mobile-demo" class="right sidenav-trigger"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
                <li>
                    <form action="search.html">
                        <div class="input-field">
                            <input id="search" type="search" required>
                            <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                            <i class="material-icons">close</i>
                        </div>
                    </form>
                </li>
                <li><a href="{% url 'music:home' %}"><i class="material-icons left">album</i>Albums</a></li>
                <li><a href="#"><i class="material-icons left">music_note</i>Songs</a></li>
                <li><a href="{% url 'music:album-create' %}"><i class="material-icons left">add</i>Add Album</a></li>
                <li><a href="#"><i class="material-icons left">exit_to_app</i>Logout</a></li>
            </ul>
        </div>
    </div>
</nav>

<ul class="sidenav" id="mobile-demo">
    <li>
        <form action="search.html">
            <div class="input-field">
                <input id="search" type="search" required>
                <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                <i class="material-icons">close</i>
            </div>
        </form>
    </li>
    <li><a href="{% url 'music:home' %}"><i class="material-icons left">album</i>Albums</a></li>
    <li><a href="#"><i class="material-icons left">music_note</i>Songs</a></li>
    <li><a href="{% url 'music:album-create' %}"><i class="material-icons left">add</i>Add Album</a></li>
    <li><a href="#"><i class="material-icons left">exit_to_app</i>Logout</a></li>
</ul>

<div class="container mt-40">
    {% block content %}
    {% endblock content %}
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script src="{% static 'music/script.js' %}"></script>
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}

{% block title %} Album Detail {% endblock %}

{% block content %}

{% if error_messages %}
<p><strong>{{ error_messages }}</strong></p>
{% endif %}

<div class="row">
    <div class="col s12 m4 l3 centered">
        <img class="w-100" src="{{ album.album_logo.url }}" alt="">
        <h5>{{ album }} - {{ album.artist }}</h5>
        <p><small>Genre: {{ album.genre }}</small></p>
    </div>

    <div class="col s12 m8 l9">
        <table>
            <thead>
            <tr>
                <th>Title</th>
                <th>Audio File</th>
                <th>Favorite</th>
                <th>Action</th>
            </tr>
            </thead>

            <tbody>
            {% for song in album.song_set.all %}
            <tr>
                <td>{{ song.song_title }}</td>
                <td>{{ song.file_type }}</td>
                <td>{{ song.is_favorite }}</td>
            </tr>
            {% endfor %}
    </div>

</div>

{% endblock content %}

music/templates/music/home.html
{% extends 'music/base.html' %}

{% block content %}
    {% if all_albums %}
            <div class="row">
                {% for album in all_albums %}
                <div class="col s12 m4 l3">
                    <div class="card card-small">
                        <div class="card-image">
                            <img src="{{ album.album_logo.url }}" alt="">
                            <span class="card-title"><strong class="title-album">{{ album.artist }} - {{ album.album_title }}</strong></span>
                        </div>
                        <div class="card-action centered">
                            <a class="btn-small blue-grey darken-4 white-text" href="{% url 'music:detail' album.id %}"><i class="material-icons">list</i></a>
                            <a class="btn-small blue darken-4 white-text" href="{% url 'music:album-update' album.id %}"><i class="material-icons">mode_edit</i></a>
                            <a class="btn-small orange darken-4 white-text" href="{% url 'music:album-delete' album.id %}"><i class="material-icons">delete</i></a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
    {% else %}
    <h3>You don't have any albums</h3>
    {% endif %}
{% endblock content%}